swagger: '2.0'
info:
  title: Pets API
  description: Really nice API for managing pets.
  version: "1.0"

host: pets-api-6jsjyo3v7a-uc.a.run.app
basePath: /v1
schemes:
    - https
produces:
    - application/json

x-google-backend:
    address: https://pets-api-6jsjyo3v7a-uc.a.run.app/

paths:
  /pets:
    get:
      operationId: getPets  
      summary: Gets all the pets. 
      responses:
          '200':
            description: A successful response
            schema:
              type: string
    
    post:
      operationId: addPet  
      summary: Add a new Pet
      responses:
        "201":
          description: Pet added succesfully.
          schema:
              type: string

       
  /pets/{pet_id}:
    get:  
      operationId: getPet  
      summary: Get a single pet based on its ID.
      responses:
        "200":
          description: Pet retrieved successfully
          schema:
              type: string
          
    delete:
      operationId: deletePet  
      summary: Delete a pet based on its ID.
      responses:
        "204":
          description: Success.
          schema:
              type: string
    patch:
      operationId: updatePet    
      summary: Update a pet.
      responses:
        "200":
          description: Change a pet based on its ID
          schema:
              type: string

